// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TodoList.Persistence.DBContext;

#nullable disable

namespace TodoList.Persistence.Migrations
{
    [DbContext(typeof(TodoContext))]
    [Migration("20240928103929_Add_ValueObject_Description_Metadata")]
    partial class Add_ValueObject_Description_Metadata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TodoList.Domain.Entities.TodoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TodoItems");
                });

            modelBuilder.Entity("TodoList.Domain.Entities.TodoItem", b =>
                {
                    b.OwnsOne("TodoList.Domain.ValueObject.ItemDescription", "Description", b1 =>
                        {
                            b1.Property<int>("TodoItemId")
                                .HasColumnType("int");

                            b1.Property<string>("Contributors")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("TodoItemId");

                            b1.ToTable("TodoItems");

                            b1.WithOwner()
                                .HasForeignKey("TodoItemId");
                        });

                    b.OwnsOne("TodoList.Domain.ValueObject.Metadata", "Metadata", b1 =>
                        {
                            b1.Property<int>("TodoItemId")
                                .HasColumnType("int");

                            b1.Property<string>("Author")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("CreatedDate")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime>("LastModifiedDate")
                                .HasColumnType("datetime2");

                            b1.HasKey("TodoItemId");

                            b1.ToTable("TodoItems");

                            b1.WithOwner()
                                .HasForeignKey("TodoItemId");
                        });

                    b.Navigation("Description");

                    b.Navigation("Metadata");
                });
#pragma warning restore 612, 618
        }
    }
}
